*here, after using the connect option in the nb, to check the cou info we are allocated, use the command below.*

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

to get the **RAM info**, code below


In [ ]:
!cat /proc/meminfo

MemTotal:       13289424 kB
MemFree:         8055468 kB
MemAvailable:   12303052 kB
Buffers:          418536 kB
Cached:          4005412 kB
SwapCached:            0 kB
Active:           744656 kB
Inactive:        4226644 kB
Active(anon):       1416 kB
Inactive(anon):   547860 kB
Active(file):     743240 kB
Inactive(file):  3678784 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               308 kB
Writeback:             0 kB
AnonPages:        547420 kB
Mapped:           326540 kB
Shmem:              1916 kB
KReclaimable:     132996 kB
Slab:             172684 kB
SReclaimable:     132996 kB
SUnreclaim:        39688 kB
KernelStack:        5216 kB
PageTables:         8320 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6644712 kB
Committed_AS:    2596628 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11848 kB
VmallocChunk:    

 to ***install all the libraries*** needed for google colab
 1. pandas

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Soil Nutrients.csv')

In [ ]:
df.head()

Name Fertility       Photoperiod  Temperature    Rainfall        pH  \
0  Strawberry  Moderate       Day Neutral    20.887923  747.860765  6.571548   
1  Strawberry  Moderate       Day Neutral    18.062721  711.104329  6.251806   
2  Strawberry  Moderate  Short Day Period    16.776782  774.038247  6.346916   
3  Strawberry  Moderate  Short Day Period    14.281000  665.633506  6.259598   
4  Strawberry  Moderate       Day Neutral    21.444490  806.531455  6.384368   

   Light_Hours  Light_Intensity         Rh    Nitrogen  Phosphorus  \
0    13.091483       533.762876  91.197196  170.800381  118.670058   
1    13.063016       505.789101  91.939623  179.290364  121.020244   
2    12.945927       512.985617  91.387286  181.440732  116.936806   
3    13.318922       484.860067  91.254598  176.165282  122.233153   
4    13.312915       512.747307  92.354829  182.935334  126.088234   

    Potassium      Yield Category_pH Soil_Type  Season  N_Ratio  P_Ratio  \
0  243.331211  20.369555  low_acidic      Loam  Summer     10.0     10.0   
1  246.910378  20.402751  low_acidic      Loam  Spring     10.0     10.0   
2  242.699601  19.158847  low_acidic      Loam  Summer     10.0     10.0   
3  237.096892  20.265745  low_acidic      Loam  Summer     10.0     10.0   
4  243.880364  20.397336  low_acidic      Loam  Spring     10.0     10.0   

   K_Ratio  
0     10.0  
1     10.0  
2     10.0  
3     10.0  
4     10.0

**NumPy** - numerical python
1. allows several mathematical operations
2. faster opertions

In [ ]:
import numpy as np

numpy arrays

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

creating one dimensional array

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

creating a 2 dimensional array

In [ ]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
b.shape

(2, 5)

In [ ]:
c = np.array([(1,2,3,4,),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((5,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#making an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


creating a numpy array with random values

In [ ]:
d = np.random.random((3,4))
print(d)

[[0.08275816 0.62264281 0.31332319 0.64760347]
 [0.54697521 0.70939797 0.63565719 0.1363742 ]
 [0.18924213 0.82515646 0.4379765  0.81467509]]


randomn interger value within a specific range

In [ ]:
import numpy as np
e = np.random.randint(10,100,(3,5))

In [ ]:
print(e)

[[55 42 30 37 59]
 [71 83 14 83 10]
 [90 58 33 36 50]]


array of evenly spaced values

In [ ]:
f = np.linspace(10,30,5)
print(f)

[10. 15. 20. 25. 30.]


array of evenly spaced values --> specifying the step

In [ ]:
g = np.arange(10,30,5)
print(g)

[10 15 20 25]


convert a list to numpy array

In [ ]:
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[87 64 76 15 87]
 [74 24 58 37 13]
 [40 20 23 21 27]
 [80 61 22 46 80]
 [20 89 66 37 80]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
#checking the data type of values in the array
print(c.dtype)

int64


mathematical operations on np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)      #only concatinates the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[1 5 2]
 [4 1 5]
 [4 9 8]]
[[18 18 12]
 [15 12 11]
 [19 13 11]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#here in np array basic operations occur like this

[[19 23 14]
 [19 13 16]
 [23 22 19]]
[[-17 -13 -10]
 [-11 -11  -6]
 [-15  -4  -3]]
[[ 18  90  24]
 [ 60  12  55]
 [ 76 117  88]]
[[0.05555556 0.27777778 0.16666667]
 [0.26666667 0.08333333 0.45454545]
 [0.21052632 0.69230769 0.72727273]]


array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 4 4]
 [0 6 7]]
(2, 3)


transpose

In [2]:
import numpy as np
array = np.random.randint(0,10,(2,3))
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 0]
 [7 8]
 [6 4]]
(3, 2)
